### PR TITLE
Add check doc

### PR DESCRIPTION
**Pull request by dcastrowa**
### Description:

Adds documentation for checks that previously did not have available.
Checks with newly added documentation:
- BigNodeBadDataCheck
- LineCrossingBuildingCheck
- LineCrossingWaterBodyCheck (documentation was already available but needed to be linked)
- UnwalkableWaysCheck
- InconsistentRoadClassificationCheck

### CODE REVIEW

**Review by atiannicelli — APPROVED** [review]
Awesome. Any chance you want to add OverlappingEdgeCheck ? :)

**Comment by dcastrowa** [comment]
> Awesome. Any chance you want to add OverlappingEdgeCheck ? :)

I am currently working on adding all missing documentation but a few at a time so it's not one large PR. If you feel that having documentation for OverlappingEdgeCheck is important I can definitely add it before today's release. Otherwise, I will make sure to include it in my next PR.

**Comment by atiannicelli** [comment]
> > Awesome. Any chance you want to add OverlappingEdgeCheck ? :)
> 
> I am currently working on adding all missing documentation but a few at a time so it's not one large PR. If you feel that having documentation for OverlappingEdgeCheck is important I can definitely add it before today's release. Otherwise, I will make sure to include it in my next PR.

Oh, sweet. if you are on a mission to add more then I'm happy knowing that it is in the works. No need to add it to this one.

**Review by mattmanley — APPROVED** [review]
LGTM. Thanks Dan!

**Pull request merged**
