### PR TITLE
Fix aws script timeout and convert inputFolder to input

### PR DESCRIPTION
**Pull request by atiannicelli**
### Description:

Fix AWS script to wait full number of minutes.
Move away from deprecated -inputFolder parameter.

### Potential Impact:

Without this change the script waits only 5 hours instead of 100 hours.

### Unit Test Approach:

Saw this failure because of an extra long run that timed out. Retested with latest code and it allowed it to complete.

### Test Results:

NA

### CODE REVIEW

**Review by tsmock — COMMENTED** [review]
This looks good to me.

**Review by Bentleysb — APPROVED** [review]

**Comment by dcastrowa** [comment]
@tsmock I am working on releasing a new version today. If you have the capacity can you give this a review? Thanks!

**Comment by atiannicelli** [comment]
> @tsmock I am working on releasing a new version today. If you have the capacity can you give this a final review? Thanks!

@dcastrowa - I think you are in the wrong PR. Taylor already reviewed this and accepted this one 6 days ago.

**Comment by dcastrowa** [comment]
> > @tsmock I am working on releasing a new version today. If you have the capacity can you give this a final review? Thanks!
> 
> @dcastrowa - I think you are in the wrong PR. Taylor already reviewed this and accepted this one 6 days ago.

Ok thanks for the update. I was waiting on the green check mark.

**Review by sayas01 — APPROVED** [review]

**Pull request merged**
