### PR TITLE
LevelCrossingOnRailwayCheck refinement

### PR DESCRIPTION
**Pull request by vladlemberg**
### Description:

Please refer to: https://github.com/osmlab/atlas-checks/issues/577

### Potential Impact:
1) assigning "disuse" to a Node if railway is disused.
2) adding minimum highway type for configuration.json

### Unit Test Approach:

created unit test for following scenarios:
- minimum highway type
- railway=disuse case 

### Test Results:
passed

### CODE REVIEW

**Comment by vladlemberg** [comment]
@sayas01, @Bentleysb, could you please check the sonar bug ? this is strange... do I need to refactor the code to satisfy sonar ?

**Comment by Bentleysb** [comment]
@vladlemberg, as this bug is covered in a different way by the API you can suppress the sonar check for that method. See an example of this here: https://github.com/osmlab/atlas-checks/blob/dev/src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/InvalidPiersCheck.java#L129

**Review by Bentleysb — APPROVED** [review]
The overall flow of how the railwayTag fields get used is a bit odd, but it works. It might be nice to have some comments just to point out how those are getting used.

**Comment by vladlemberg** [comment]
> The overall flow of how the railwayTag fields get used is a bit odd, but it works. It might be nice to have some comments just to point out how those are getting used.

@Bentleysb, I believe there is no usage of disused tag. The purpose of this change is assigning correct tag with Autofix

**Review by sayas01 — APPROVED** [review]
LGTM!

**Pull request merged**
