### PR TITLE
MultipleValuesInKeyCheck OSMOSE 9005 

### PR DESCRIPTION
**Pull request by mselaineleong**
### Description:

This PR is to address OSMOSE 9005:
Class 9005001 "{0.key} with multiple values" 
Class 9005002 "empty value in semicolon-separated {0.key}" 

e.g. the following are examples of tags that are flagged by OSMOSE 9005:

- lanes with multiple values 
lanes = 1;2;3 

- name with multiple values 
name = Historica;Marker 
name = 4;22 

- highway with multiple values 
highway = traffic_signals;crossing 

- addr:street with multiple values 
addr:street = Fagerquist Rd; Wolf Ln; Pearce Lane 

- maxspeed with multiple values 
maxspeed = 40;50  

- water with multiple values 
water = service;cattle 

- telecom:medium with multiple values 
telecom:medium = fibre;copper 

- begins with semicolons
source = ;survey 

- ends with semicolons
cuisine = noodle;soba; 

- empty value in semicolon-separated tag
cuisine = noodle;    ;soba; 

So REGEX filters have been added with 4 separate cases to make sure the instructions are clear with potential Auto-Fix capabilities. This is a resource update for InvalidTagsCheck.

Case 1: Tags should NOT allow MULTIPLE VALUES (e.g. maxspeed = 40;50). True positive if true. 
Case 2: Tags should NOT START WITH semicolons (e.g. source = ;survey). True positive if true. 
Case 3: Tags should NOT END WITH semicolons (e.g. source_ref = http://wiki.osm.org/wiki/GSI_KIBAN;). True positive if true.  
Case 4: Tags should NOT have empty values IN BETWEEN semicolons. (e.g. example;;example or example; ;example) True positive if true.  

### Test Results:

| ISO | Total Flags | Sampled  | Sampling % | TP | FP | False Positive Rate |
|-----|-------------|----------|------------|----|----| ------------------- |
|  AUS  |    477         |    200      |     42%       |   200 |   0 | 0%   |
|  PRT   |    283         |    100      |     35%       |   100 |   0 | 0%   |
|  DZA  |    799         |    200      |     25%       |   200 |   0 | 0%   |
|  ROU |    292         |    35      |     12%       |   35 |   0 | 0%   |
|  TUR  |    161         |    87      |     54%       |   87 |   0 | 0%   |
|  FIN   |    298         |    200      |     67%       |   100 |   0 | 0%   |
|  COL  |    776         |    200      |     26%       |   200 |   0 | 0%   |

### CODE REVIEW

**Comment by Bentleysb** [comment]
@mselaineleong, this looks great. Thanks for all the test results. Just one request, could you add more detail to the PR description? While knowing that this covers osmose check 9005 does describe what is being added, it is not the most clear. A description of the use cases in the data this is trying to cover would be great, as apposed to the osmose code it is trying to replicate. It would also be great to mention this is a configuration/resource update for InvalidTagsCheck.

**Comment by mselaineleong** [comment]
> @mselaineleong, this looks great. Thanks for all the test results. Just one request, could you add more detail to the PR description? While knowing that this covers osmose check 9005 does describe what is being added, it is not the most clear. A description of the use cases in the data this is trying to cover would be great, as apposed to the osmose code it is trying to replicate. It would also be great to mention this is a configuration/resource update for InvalidTagsCheck.

Thanks @Bentleysb The PR description has been fixed as suggested!

**Review by Bentleysb — APPROVED** [review]
Awesome, thanks.

**Review by sayas01 — APPROVED** [review]
This looks great!

**Pull request merged**
