### PR TITLE
Conflicting Area Tag Combination check

### PR DESCRIPTION
**Pull request by danielduhh**
This check flags mutually exclusive tag combinations on Atlas Area objects.

This PR includes check code, config, tests & documentation..

For live examples, see: https://github.com/danielduhh/atlas-checks/blob/dev-cat/docs/checks/conflictingAreaTagCombination.md#live-example

### CODE REVIEW

**Comment by danielduhh** [comment]
Looks like this PR depends on [atlas v 5.0.16](https://github.com/osmlab/atlas/releases/tag/5.0.16)

I can close it for now until the atlas dependency get's bumped up @jklamer

**Comment by jklamer** [comment]
@danielduhh When the new atlas is released, just be sure to update the dependencies.gradle in this PR and the build should pass. Then we can merge them at the same time without closing this one.

**Comment by jklamer** [comment]
@danielduhh looks like they have released up to 5.1.2 (I believe), can you update to the latest?

**Comment by danielduhh** [comment]
@jklamer Will do! Looks like the latest is [5.1.1](https://github.com/osmlab/atlas/releases)

**Comment by jklamer** [comment]
thank you!

**Pull request merged**
