### PR TITLE
add more common methods and unittest

### PR DESCRIPTION
**Pull request by vladlemberg**
### Description:

Please refer: https://github.com/osmlab/atlas-checks/issues/448

### Potential Impact:

remove code redundancy 

### Unit Test Approach:

cover each method. 

### Test Results:

passed.

### CODE REVIEW

**Review by Bentleysb — APPROVED** [review]

**Review by Bentleysb — APPROVED** [review]

**Comment by Bentleysb** [comment]
@vladlemberg, we will be looking to get this into tomorrows release.

**Review by sayas01 — APPROVED** [review]
Looks good!

**Comment by ameliaewatts** [comment]
@vladlemberg Because this is still using the previous Travis framework, in order to pass, we need to close it and reopen this pr or push a new commit!

**Comment by matthieun** [comment]
Closing and re-opening.

**Pull request merged**
