### PR TITLE
Bump version to 6.1.8 and update changelog

### PR DESCRIPTION
**Pull request by dcastrowa**
### Description:

Bump version for next release.

### CODE REVIEW

**Review by Bentleysb — APPROVED** [review]

**Comment by atiannicelli** [comment]
Don't we need an update to the changelog along with this bump?

**Comment by dcastrowa** [comment]
Thats a good point. I will get the changelog up to date.

**Comment by atiannicelli** [comment]
Thanks for adding the 6.17 changes to the log. 
Since we are bumping to 6.1.8, shouldn't the changelog also include the new changes to 6.1.8?

**Comment by dcastrowa** [comment]
6.1.7 was just released yesterday. Generally, the next version is bumped ahead of time in order to avoid waiting for approval during the release process. We are on schedule to release 6.1.8 on 12/2.

**Review by ameliaewatts — APPROVED** [review]
Good work!

**Review by Bentleysb — APPROVED** [review]

**Pull request merged**
